### PR TITLE
Make fetch happen

### LINKED ISSUE #117: Use make-fetch-happen instead of node-fetch when downloading compiler
The package cannot be used on Windows computers behind a corporate proxy as it is common in many companies. npm itself can download all packages, but `download-compiler-for-end-user.js` does not respect the proxy configuration.

```
Running 'npm install --https-proxy=http://<my-proxy>:8080 --proxy=http://<my-proxy>:8080 --noproxy=localhost' in <my-path>
npm ERR! code 1
npm ERR! path <my-path>\node_modules\sass-embedded
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node ./download-compiler-for-end-user.js
npm ERR! Downloading dart-sass-embedded release asset.
npm ERR! FetchError: request to https://github.com/sass/dart-sass-embedded/releases/download/1.49.9/sass_embedded-1.49.9-windows-x64.zip failed, reason: connect ECONNREFUSED <ip>:<port>
npm ERR!     at ClientRequest.<anonymous> (<my-path>\node_modules\node-fetch\lib\index.js:1491:11)
npm ERR!     at ClientRequest.emit (node:events:526:28)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:442:9)
npm ERR!     at TLSSocket.emit (node:events:526:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
npm ERR!   type: 'system',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   code: 'ECONNREFUSED'
npm ERR! }
```

### PR DESCRIPTION
**Pull request by chrisuehlinger-techslice**
Resolves #117. I also ran into some race conditions occasionally when running `npm run init`, and it looks like there were some `fs.rename()` calls whose promises weren't being awaited, so I added `await`s for those. I checked that in as a separate commit in case you'd prefer I split this into two PRs.

### CODE REVIEW

**Comment by chrisuehlinger-techslice** [comment]
@jathak and @nex3 (This is my first time submitting an OSS PR in a while, not sure if I'm supposed to tag maintainers to request a review, just wanted to make sure y'all are aware of this)

File: tool/utils.ts [hunk 1]
```diff
@@ -2,9 +2,9 @@
 // MIT-style license that can be found in the LICENSE file or at
 // https://opensource.org/licenses/MIT.
 
+const fetch = require('make-fetch-happen').defaults();
```
Comment (jathak) [inline tool/utils.ts:5]: Please use an `import` statement here and then assign fetch below the imports.

e.g. something like:
```ts
import {defaults as initMakeFetchHappen} 'make-fetch-happen';
// other imports
const fetch = initMakeFetchHappen();
```

**Review by jathak — COMMENTED** [review]
Thanks for this!

**Review by nex3 — APPROVED** [review]
