### PR TITLE
Percent encode relative path like url.pathToFileURL

### LINKED ISSUE #133: sourcemap `sources` field gets url encoded
When a file is in a directory with a name including `@`, the `sources` field in sourcemap gets url encoded.
This does not happen with dart-sass.

```txt
.
└── src
    ├── @dir
    │   └── bar.scss
    └── foo.scss
```

```js
sass.render({
  file: path.resolve('src/foo.scss'),
  outFile: path.resolve('dist/foo.css'),
  sourceMap: true
})

sass.render({
  file: 'src/foo.scss',
  outFile: 'dist/foo.css',
  sourceMap: true
})
```

```text
[dart-sass] with resolve
{"version":3,"sourceRoot":"","sources":["../src/@dir/bar.scss","../src/foo.scss"],"names":[],"mappings":"AAAA;EACE;;;ACCF;EACE","file":"foo.css"}

-----------
[sass-embedded] with resolve
{"version":3,"sourceRoot":"","sources":["../src/%40dir/bar.scss","../src/foo.scss"],"names":[],"mappings":"AAAA;EACE;;;ACCF;EACE","file":"foo.css"}

-----------
[dart-sass] without resolve
{"version":3,"sourceRoot":"","sources":["file:///D:/documents/GitHub/sass-embedded-atmark-sourcemap-reproduction/src/@dir/bar.scss","file:///D:/documents/GitHub/sass-embedded-atmark-sourcemap-reproduction/src/foo.scss"],"names":[],"mappings":"AAAA;EACE;;;ACCF;EACE","file":"foo.css"}

-----------
[sass-embedded] without resolve
{"version":3,"sourceRoot":"","sources":["../src/%40dir/bar.scss","../src/foo.scss"],"names":[],"mappings":"AAAA;EACE;;;ACCF;EACE","file":"foo.css"}
```

### Step to reproduce
1. Clone https://github.com/sapphi-red/sass-embedded-atmark-sourcemap-reproduction.
2. Run `npm i`.
3. Run `node sass.js`
4. See output.

### PR DESCRIPTION
**Pull request by ntkme**
Fixes #133.

### CODE REVIEW

File: lib/src/utils.ts [hunk 1]
```diff
@@ -90,8 +90,14 @@ export function valueError(message: string, name?: string): Error {
...
 
-  const components = p.sep === '\\' ? path.split(/[/\\]/) : path.split('/');
-  return components.map(encodeURIComponent).join('/');
+  // percent encode relative path like `pathToFileURL`
+  return encodeURI(path)
+    .replace(/[#?]/g, encodeURIComponent)
+    .replace(
+      process.platform === 'win32' ? /%(5B|5C|5D|5E|7C)/g : /%(5B|5D|5E|7C)/g,
+      decodeURIComponent
+    )
```
Comment (nex3) [inline lib/src/utils.ts:99]: I think this is supposed to be `encodeURIComponent`... currently this will convert the path `%5B` to the URL `[`, when it should be converted to `%255B`.

File: lib/src/utils.test.ts [hunk 2]
```diff
@@ -0,0 +1,19 @@
+import {pathToFileURL} from 'url';
+import {pathToUrlString} from './utils';
+
+describe('utils', () => {
+  describe('pathToUrlString', () => {
+    it('encode relative path like `pathToFileURL`', () => {
```
Comment (nex3) [inline lib/src/utils.test.ts:6]: Add a test for percent-encoding paths that are already percent-encoded, so we'll catch issues like the one below.

**Review by nex3 — CHANGES_REQUESTED** [review]

File: lib/src/utils.ts (hunk 1 above)
Comment (ntkme) [reply lib/src/utils.ts:99]: This is intended. `pathname` of URL has a different [percent-encode set](https://url.spec.whatwg.org/#path-percent-encode-set) that some of the character does not need to be escaped.

Comment (ntkme) [reply lib/src/utils.ts:99]: And it will not encode `%5B` to `[` because first `%` will be encoded as `%25` first, thus there is no `%5B` to be replaced.

File: lib/src/utils.test.ts (hunk 2 above)
Comment (ntkme) [reply lib/src/utils.test.ts:6]: Added.

**Comment by nex3** [comment]
Ah, I understand now. Thanks!
