### PR TITLE
Stricter checks in `LegacyColor` constructor

### LINKED ISSUE #348: `LegacyColor` has incorrect RGB values when either green or blue are zero
For example, the hex code `#ff0000` is just red, no green or blue, and is equivalent to `rgb(255, 0, 0)`. Constructing an instance of `LegacyColor` with these values results in `r == 0, g == 0, b == 255`:

```ts
new LegacyColor(255, 0, 0)
/*
sass.types.Color {
  inner: SassColor {
    redInternal: 0,
    greenInternal: 0,
    blueInternal: 255,
    alphaInternal: 1
  }
}
*/
```

I'm pretty sure [this line is the culprit](https://github.com/sass/embedded-host-node/blob/main/lib/src/legacy/value/color.ts#L25). If either `green` or `blue` are falsy, which `0` is, then the code acts as if the `constructor(argb: number)` variant was called. I think these should be stricter checks so that `0` doesn't trigger the wrong logical branch.

I understand that this is a deprecated API but I'd love to see it be fixed. I'd be happy to put together a pull request if you'd like.

Thanks in advance!

### PR DESCRIPTION
**Pull request by mrdziuban**
Fixes #348 

Rather than just checking if `green` or `blue` are falsy, the code now checks if they're `undefined` or `null`.

### CODE REVIEW

File: lib/src/legacy/value/color.ts [hunk 1]
```diff
@@ -22,7 +22,7 @@ export class LegacyColor extends LegacyValueBase<SassColor> {
     }
 
     let red: number;
-    if (!green || !blue) {
+    if (green == undefined || blue == undefined) {
```
Comment (ntkme) [inline lib/src/legacy/value/color.ts:25]: Use triple equal instead of double equal:

```suggestion
    if (green === undefined || blue === undefined) {
```

**Review by ntkme — CHANGES_REQUESTED** [review]

File: lib/src/legacy/value/color.ts (hunk 1 above)
Comment (mrdziuban) [reply lib/src/legacy/value/color.ts]: Got it, just pushed a change to explicitly check for both `undefined` and `null`

File: lib/src/legacy/value/color.ts [hunk 2]
```diff
@@ -5,6 +5,10 @@
 import {SassColor} from '../../value/color';
 import {LegacyValueBase} from './base';
 
+function isUndefinedOrNull<A>(a: A): boolean {
+  return a === undefined || a === null;
+}
```
Comment (nex3) [inline lib/src/legacy/value/color.ts:10]: Please document this, and put it in `utils.ts`

File: lib/src/legacy/value/color.ts [hunk 3]
```diff
@@ -5,6 +5,10 @@
 import {SassColor} from '../../value/color';
 import {LegacyValueBase} from './base';
 
+function isUndefinedOrNull<A>(a: A): boolean {
```
Comment (nex3) [inline lib/src/legacy/value/color.ts:8]:
```suggestion
function isUndefinedOrNull(a: unknown): boolean {
```

**Review by nex3 — CHANGES_REQUESTED** [review]

**Review by nex3 — APPROVED** [review]
